using MiniExcelLibs;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;

namespace ProjectHD.Editor
{
    public static class EditorExcelToData
    {
        //public static Dictionary<string, ExcelTable> CachedTable = new();
        public static Dictionary<string, IEnumerable<IDictionary<string, object>>> CachedTable = new();

        public static List<string> autoGeneratedClassNames = new();
        public const string GenerateCodePath = "/GenerateCode/Data/";
        public const string GenerateEditorCodePath = "/GenerateCode/Editor/";
        public const string GenerateMainCodePath = "/GenerateCode/";
        public const string CommandChar = "@";
        public static bool SheetImportFromPath(string sheetAssetPath)
        {
            if (string.IsNullOrEmpty(sheetAssetPath)) return true;
            if (string.IsNullOrWhiteSpace(sheetAssetPath)) return true;

            var tableNames = MiniExcel.GetSheetNames(sheetAssetPath);

            foreach (var tableName in tableNames)
            {
                var rawTable = MiniExcel.Query(sheetAssetPath, sheetName: tableName, useHeaderRow: true).ToList();

                var table = rawTable
                    .Select(row => row as IDictionary<string, object>)
                    .Where(row => row != null)
                    .ToList();

                if (CachedTable.ContainsKey(tableName))
                {
                    CachedTable[tableName] = table;
                    Debug.LogWarning($"{sheetAssetPath}에서 {tableName}가 중복되어 데이터 교체하였습니다.");
                }
                else
                {
                    CachedTable.Add(tableName, table);
                }
            }

            return false;
        }

        public static void CashingExcelDatas(List<string> sheetPaths)
        {
            CachedTable.Clear();
            for (int i = 0; i < sheetPaths.Count; i++)
            {
                SheetImportFromPath(sheetPaths[i]);
            }
        }
        public static void CashingExcelData(string sheetPaths)
        {
            CachedTable.Clear();
            SheetImportFromPath(sheetPaths);
        }

        public static void ClearTable()
        {
            CachedTable.Clear();
            autoGeneratedClassNames.Clear();
        }

        private static void WriteTextToFile(string text, string filePath)
        {
            FileInfo dic = new FileInfo(filePath);
            if (false == dic.Directory.Exists)
            {
                dic.Directory.Create();
            }
            System.IO.File.WriteAllText(filePath, text);
        }

        public static List<string> ExtractStrings(string code)
        {
            // 정규 표현식 패턴: 쌍따옴표 안에 있는 문자열을 매칭
            string pattern = "\"([^\"]*)\"";
            MatchCollection matches = Regex.Matches(code, pattern);

            HashSet<string> extractedStrings = new HashSet<string>();
            foreach (Match match in matches)
            {
                extractedStrings.Add(match.Groups[1].Value);
            }

            return new List<string>(extractedStrings);
        }

        public static bool ConvertExcelToJson(ref List<string> addedPath)
        {
            var temp = new Dictionary<string, EditorGenerateCode.ITableImporter>();
            var isNewData = false;
            foreach (var (tableName, table) in CachedTable)
            {
                var sheetCommand = tableName.Split(CommandChar);
                if (!temp.TryGetValue(sheetCommand[0], out var importer)) continue;
                isNewData |= importer.ImportTable(sheetCommand[0], table, ref addedPath);
            }
            return isNewData;
        }
    }
}
