using System;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using MessagePack;
using MasterMemory;

namespace ProjectHD.Editor
{
    public static class TableImporterGeneratorEditor
    {
        private const string DataNamespace = "ProjectHD.Data";
        private const string ClassNamespace = "ProjectHD";
        private const string OutputPath = "Assets/Scripts/ProjectHD/Editor/AutoGenerated/GeneratedTableImporters.cs";

        [MenuItem("Tools/Generate/Table Importers")]
        public static void GenerateTableImporters()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// 자동 생성된 코드입니다. 수정하지 마세요.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ClassNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GeneratedTableImporters");
            sb.AppendLine("    {");

            var allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a =>
                {
                    try { return a.GetTypes(); }
                    catch (ReflectionTypeLoadException e) { return e.Types.Where(t => t != null); }
                })
                .Where(t => t != null
                            && t.Namespace != null
                            && t.Namespace.StartsWith(DataNamespace, StringComparison.Ordinal)
                            && t.GetCustomAttribute<MessagePackObjectAttribute>()?.KeyAsPropertyName == true
                            && t.GetCustomAttribute<MemoryTableAttribute>() != null)
                .OrderBy(t => t.Name)
                .ToList();

            foreach (var type in allTypes)
            {
                sb.AppendLine($"        #region {type.Name}");
                sb.AppendLine();
                sb.AppendLine($"        public static bool TryConvertTableToData(IEnumerable<IDictionary<string, object>> table, out {type.FullName}[] data)");
                sb.AppendLine("        {");
                sb.AppendLine($"            data = TableConverter.ConvertTableTo<{type.FullName}>(table);");
                sb.AppendLine("            return data != null;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = System.IO.Path.GetDirectoryName(OutputPath);
            if (!System.IO.Directory.Exists(dir))
                System.IO.Directory.CreateDirectory(dir);

            var newCode = sb.ToString();
            var needSave = true;

            // 기존 파일과 비교
            if (System.IO.File.Exists(OutputPath))
            {
                var oldCode = System.IO.File.ReadAllText(OutputPath, Encoding.UTF8);
                if (oldCode == newCode)
                {
                    needSave = false;
                    Debug.Log($"⚡ 변경 사항이 없어 파일을 갱신하지 않았습니다. (총 {allTypes.Count}개 메서드)");
                }
            }

            if (needSave)
            {
                System.IO.File.WriteAllText(OutputPath, newCode, Encoding.UTF8);
                AssetDatabase.Refresh();
                Debug.Log($"✅ Table Importers 코드 생성 완료: {OutputPath} (총 {allTypes.Count}개 메서드)");
            }
        }
    }
}